### ISSUE TITLE
Image File Truncated

### ISSUE THREAD

**Issue by ddsky** [bjoern-hempel/keras-machine-learning-framework#2]
When trying to run the learning command, I get `OSError: image file is truncated (5 bytes not processed)`.

I found this https://github.com/eriklindernoren/PyTorch-YOLOv3/issues/162 but don't know where to change it, can you help?

Full Stack Trace:
```
Epoch 00001: LearningRateScheduler setting learning rate to 0.001.
   41/10876 [..............................] - ETA: 54:06:43 - loss: 8.2513 - acc: 0.0579 - top_k_categorical_accuracy: 0.0655Traceback (most recent call last):
  File "C:\Users\david\.conda\envs\keras-gpu\Scripts\ml-script.py", line 11, in <module>
    load_entry_point('machineLearning', 'console_scripts', 'ml')()
  File "C:\Users\david\.conda\envs\keras-gpu\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\david\.conda\envs\keras-gpu\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "C:\Users\david\.conda\envs\keras-gpu\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\david\.conda\envs\keras-gpu\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\david\.conda\envs\keras-gpu\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\david\.conda\envs\keras-gpu\lib\site-packages\click\decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "C:\Users\david\.conda\envs\keras-gpu\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\users\david\keras-machine-learning-framework\mlks\main.py", line 89, in cli_train
    train_class.do()
  File "c:\users\david\keras-machine-learning-framework\mlks\commands\image_classifier\train\main.py", line 121, in do
    history = self.train(model, train_generator, validation_generator)
  File "c:\users\david\keras-machine-learning-framework\mlks\commands\image_classifier\main.py", line 764, in train
    model_checkpoint
  File "C:\Users\david\.conda\envs\keras-gpu\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\david\.conda\envs\keras-gpu\lib\site-packages\keras\engine\training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)
  File "C:\Users\david\.conda\envs\keras-gpu\lib\site-packages\keras\engine\training_generator.py", line 181, in fit_generator
    generator_output = next(output_generator)
  File "C:\Users\david\.conda\envs\keras-gpu\lib\site-packages\keras\utils\data_utils.py", line 709, in get
    six.reraise(*sys.exc_info())
  File "C:\Users\david\.conda\envs\keras-gpu\lib\site-packages\six.py", line 693, in reraise
    raise value
  File "C:\Users\david\.conda\envs\keras-gpu\lib\site-packages\keras\utils\data_utils.py", line 685, in get
    inputs = self.queue.get(block=True).get()
  File "C:\Users\david\.conda\envs\keras-gpu\lib\multiprocessing\pool.py", line 644, in get
    raise self._value
  File "C:\Users\david\.conda\envs\keras-gpu\lib\multiprocessing\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\david\.conda\envs\keras-gpu\lib\site-packages\keras\utils\data_utils.py", line 626, in next_sample
    return six.next(_SHARED_SEQUENCES[uid])
  File "C:\Users\david\.conda\envs\keras-gpu\lib\site-packages\keras_preprocessing\image\iterator.py", line 104, in __next__
    return self.next(*args, **kwargs)
  File "C:\Users\david\.conda\envs\keras-gpu\lib\site-packages\keras_preprocessing\image\iterator.py", line 116, in next
    return self._get_batches_of_transformed_samples(index_array)
  File "C:\Users\david\.conda\envs\keras-gpu\lib\site-packages\keras_preprocessing\image\iterator.py", line 230, in _get_batches_of_transformed_samples
    interpolation=self.interpolation)
  File "C:\Users\david\.conda\envs\keras-gpu\lib\site-packages\keras_preprocessing\image\utils.py", line 132, in load_img
    img = img.resize(width_height_tuple, resample)
  File "C:\Users\david\.conda\envs\keras-gpu\lib\site-packages\PIL\Image.py", line 1890, in resize
    self.load()
  File "C:\Users\david\.conda\envs\keras-gpu\lib\site-packages\PIL\ImageFile.py", line 249, in load
    "(%d bytes not processed)" % len(b)
OSError: image file is truncated (5 bytes not processed)```

**Comment by bjoern-hempel** [comment]
Hey. I think there's a broken picture in your picture set. I have integrated the suggestion (see commit: e15617051f4f3f4821461b8ebd3b95910b4c78db):

```python
ImageFile.LOAD_TRUNCATED_IMAGES = True
```

This could skip the faulty images. Can you make a pull and please try again? Thanks! :)

**Comment by bjoern-hempel** [comment]
If that doesn't work, I could integrate a check routine that finds corrupt files in advance. That would look like this:

```pyhton
from PIL import Image
from pathlib import Path

for file_path in Path('C:\\path\\to\\data\\path').glob('**/*.jpg'):
    print('Check: %s' % file_path)

    im = Image.open(file_path)
    im.verify()

    print('Done.')
```

**Comment by ddsky** [comment]
That works thank you!

One more question: how can I continue training if it gets interrupted? I have a huge dataset and one epoch takes about 40 hours. Is there a way to pick up where it left off?
